blank_issues_enabled: false
contact_links:
  - name: Start a discussion (config, doubts, docs)
    url: https://github.com/mairror/telegram-bot/discussions/new
    about: If you have any questions about Mairror Telegram Bot configuration or doubts about whether you should create a feature request or bug report, or have problems with the documentation please click here to create a Discussion instead of an Issue.
